# Site settings
title: "Sumo's Lair"
description: "Killing Floor mutators and stuff."
baseurl: ""
url: "http://kingsumos.github.io"
twitter_username: sextabruta
github_username:  kingsumos

# Build settings
markdown: kramdown
permalink: pretty
